name: 'Robot Reporter'
description: 'Parses test results and sends them as comment to that specific commit that triggered tests'
runs:
  using: 'docker'
  image: docker://nopzixcross/robot-reporter:latest
